"""``ct.hpp`` C++ snippet generator.

The output is a header-only fragment that matches the AMfracture / FCM
pipeline's expectations: a ``youngsModulusFromPixel`` function plus a
``pixelToHU`` helper, all inlined from the currently loaded material
model. The generated code is intentionally simple — no templates, no
external deps — so it's trivial to paste into a downstream solver.
"""

from __future__ import annotations


def generate_ct_hpp_snippet(
    gray, hu_cal, E_map, img,
    model: str, params: dict, void_thresh: float,
    hu_air_int, hu_ref_int,
) -> str:
    """Build the ``ct.hpp`` text for the given calibration + model."""
    spacing = img.header.get_zooms()
    vox_str = ", ".join(f"{float(s):.4f}" for s in spacing[:3])
    shape   = img.shape

    if model == "linear":
        map_body = (
            f"    // Linear: E [MPa] = {params['a']} * HU + {params['b']}\n"
            f"    double hu = pixel_intensity * {hu_cal['m']:.6f} + {hu_cal['c']:.6f};\n"
            f"    if (hu < {void_thresh:.1f}) return {params.get('E_void', 0.001):.4f};\n"
            f"    return std::max({params.get('E_void', 0.001):.4f}, {params['a']} * hu + {params['b']});\n"
        )
    elif model == "power":
        map_body = (
            f"    // Power-law: E [MPa] = {params['a']} * HU^{params['b']}\n"
            f"    double hu = pixel_intensity * {hu_cal['m']:.6f} + {hu_cal['c']:.6f};\n"
            f"    if (hu < {void_thresh:.1f}) return {params.get('E_void', 0.001):.4f};\n"
            f"    double hu_clamp = std::max(hu, {params.get('hu_min_clamp', 1.0):.2f});\n"
            f"    return {params['a']} * std::pow(hu_clamp, {params['b']});\n"
        )
    elif model == "bilinear":
        map_body = (
            f"    // Bilinear: void < {params['hu_thresh']} HU\n"
            f"    double hu = pixel_intensity * {hu_cal['m']:.6f} + {hu_cal['c']:.6f};\n"
            f"    if (hu < {params['hu_thresh']:.1f}) return {params['E_void']:.4f};\n"
            f"    return {params['E_solid']:.4f};\n"
        )
    else:
        map_body = "    // Custom table mapping — implement interpolation\n    return 1.0;\n"

    snippet = f"""// ── ct.hpp snippet generated by NIfTI Tool Suite ──────────────────────────
// Material model : {model}
// Void threshold : {void_thresh:.1f} HU
// HU calibration : m = {hu_cal['m']:.6f},  c = {hu_cal['c']:.6f}
//   (HU = m * raw_intensity + c)
// Voxel spacing  : {vox_str} mm
// Volume shape   : {shape[0]} x {shape[1]} x {shape[2]}
// E units        : MPa

#include <cmath>
#include <algorithm>

// Call this for each voxel's raw pixel intensity.
// Returns Young's modulus in MPa.
inline double youngsModulusFromPixel(double pixel_intensity) {{
{map_body}}}

// Convenience: apply calibration only
inline double pixelToHU(double pixel_intensity) {{
    return pixel_intensity * {hu_cal['m']:.6f} + {hu_cal['c']:.6f};
}}

// E stats from last run:
//   E min  = {float(E_map.min()):.2f} MPa
//   E max  = {float(E_map.max()):.2f} MPa
//   E mean = {float(E_map.mean()):.2f} MPa
"""
    return snippet
